name: OX Data Hourly Collection

on:
  schedule:
    - cron: '0 * * * *'  # Run once every hour
  workflow_dispatch:     # Allow manual trigger

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Create data directory
      run: mkdir -p data
        
    - name: Run data collector
      env:
        OX_API_KEY: ${{ secrets.OX_API_KEY }}
        OX_SECRET_KEY: ${{ secrets.OX_SECRET_KEY }}
      run: python ox_hourly_collector.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Update data collection $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
        git push
